### PR TITLE
Implementation of passive scanning at LL

### PR DESCRIPTION
**Pull request by tommag**
Second attempt of submitting a PR which should be based on the good branch this time ! 

I tried to apply your suggestions, tell me if you see a problem somewhere. 

Thanks,

Tom

### CODE REVIEW

**Comment by pauloborges** [comment]
Almost done! But there are still some errors::
- `adv_report_cb_t` now has some `const` parameters, but `adv_report_cb` function in `ll-scanner` example wasn't updated.
- In several places the code still exceeds 80 characters.
- Splitted lines aren't right aligned. We assume 8 characters for TAB size.

I know that fix this kind of stuff is boring. But don't remove this branch and create a new one. My suggestion is to you to learn how to modify old commits. Read this: http://git-scm.com/book/en/Git-Tools-Rewriting-History. Any questions how to do it, I'm here to help. Just send me an email.

**Comment by pauloborges** [comment]
We lose info if we print raw data as string. So I suggest to replace `format_data` in the example for something like this:

```
static __inline const char *format_data(const uint8_t *data, uint8_t len)
{
    static char output[3 * LL_ADV_MTU_DATA + 1];
    uint8_t i;

    for (i = 0; i < len; i++)
        sprintf(output + 3*i, "%02x ", data[i]);

    output[3*i] = '\0';

    return output;
}
```

**Comment by tommag** [comment]
OK I modified my history to take your suggestions into account. 
However maybe a "formatting" commit would have been a better/cleaner idea in that case ? 

As you see I'm new to submitting pull requests and using Git to collaborate on shared projects so there is some learning curve for me...

Thank you, 

Tom

**Comment by pauloborges** [comment]
Thanks again for your PR!

I've commited two patches to fix source formatting: 6b3d4db and a3ff5c9.

**Comment by tommag** [comment]
Thank you and sorry for the bad formatting, I'll try to adapt better to your coding conventions next time !

**Pull request merged**
